### ISSUE TITLE
Wrong conversion when paragraph begins with a number

### ISSUE THREAD

**Issue by gocursor** [Adventech/adventech.io#9]
If a paragraph begins with a number (like in Slovenian translation in https://github.com/Adventech/sabbath-school-lessons/blob/stage/src/sl/2021-02/07/04.md) then your Markdown converter converts this wrongly to the "numbered list" (rendering here: https://sabbath-school.adventech.io/sl/2021-02/07/zaveza-na-sinaju/). But the Slovenian text "2. Mojzesova knjiga..." is referring to the book of Exodus and is a normal paragraph - not a numbered list...

**Comment by gocursor** [comment]
"2 Mojzesova knjiga" is grammatically incorrect in Slovenian language. It reads like "two book of moses" and not as "second book of moses". And even if it would be an alternative option, one would need to communicate such Markdown rules with Slovenian translators. Maybe you can add some additional checks for such cases in the software and then manually modify Markdown files to avoid such conversion (but without changing the translation text)...

**Comment by merlin-zaraza** [comment]
I think we use third party software to parse/render markdown and it's hard to check things like this. The best solution is to follow markdown syntax. I suggest to add backslash-escape before dot like `2\. Mojzesova knjiga` or invisible character before the number like `&#8291;2. Mojzesova knjiga`. I can try to make changes in content and see what works.

**Comment by gocursor** [comment]
Please note, that I am just a reader of of the lessons and that I am not connected with translation team! I don't even know in what format you get the translations and who uploads them...

**Comment by merlin-zaraza** [comment]
Adventech team is working on parsing text and uploading formatted markdown here )
So we are good
